#!/usr/bin/env python3
"""
Test just the database creation part
"""

import os
from dotenv import load_dotenv
from supabase import create_client
import time

load_dotenv('apps/api/.env')

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

print("=" * 70)
print("🗄️  DATABASE TEST: Create User → Profile → Project")
print("=" * 70)

# Create test user
TEST_EMAIL = f"testuser{int(time.time())}@gmail.com"
TEST_PASSWORD = "TestPassword123!"

print(f"\n1. Creating user: {TEST_EMAIL}")
try:
    response = supabase.auth.sign_up({
        "email": TEST_EMAIL,
        "password": TEST_PASSWORD
    })
    
    if response.user:
        user_id = response.user.id
        print(f"   ✅ User created! ID: {user_id}")
    else:
        print("   ❌ Failed to create user")
        exit(1)
except Exception as e:
    print(f"   ❌ Error: {e}")
    exit(1)

# Wait a moment for trigger
print("\n2. Checking profile creation (trigger should auto-create)...")
time.sleep(1)

try:
    profile = supabase.table('profiles').select('*').eq('id', user_id).execute()
    if profile.data:
        print(f"   ✅ Profile auto-created by trigger!")
        print(f"   ✅ Email: {profile.data[0]['email']}")
    else:
        print("   ❌ Profile not created - trigger not working")
        exit(1)
except Exception as e:
    print(f"   ❌ Error: {e}")
    exit(1)

print("\n3. Creating project...")
try:
    project_data = {
        'user_id': user_id,
        'title': 'Test Project - The Future of AI',
        'topic': 'The Future of AI',
        'status': 'draft',
        'mode': 'script',
        'word_count': 500,
        'image_count': 10
    }
    
    result = supabase.table('projects').insert(project_data).execute()
    
    if result.data:
        project_id = result.data[0]['id']
        print(f"   ✅ Project created! ID: {project_id}")
        print(f"   ✅ Title: {result.data[0]['title']}")
    else:
        print("   ❌ Failed to create project")
        exit(1)
except Exception as e:
    print(f"   ❌ Error: {e}")
    exit(1)

print("\n4. Creating script manually...")
try:
    script_data = {
        'project_id': project_id,
        'raw_script': 'This is a test script generated by the test system.',
        'edited_script': 'This is a test script generated by the test system.',
        'sanitized_script': 'This is a test script generated by the test system.'
    }
    
    result = supabase.table('scripts').insert(script_data).execute()
    
    if result.data:
        script_id = result.data[0]['id']
        print(f"   ✅ Script created! ID: {script_id}")
    else:
        print("   ❌ Failed to create script")
        exit(1)
except Exception as e:
    print(f"   ❌ Error: {e}")
    exit(1)

print("\n5. Verifying all data in database...")
try:
    # Check profiles
    profiles = supabase.table('profiles').select('*').execute()
    print(f"   📊 Profiles: {len(profiles.data)} entries")
    
    # Check projects  
    projects = supabase.table('projects').select('*').execute()
    print(f"   📊 Projects: {len(projects.data)} entries")
    
    # Check scripts
    scripts = supabase.table('scripts').select('*').execute()
    print(f"   📊 Scripts: {len(scripts.data)} entries")
    
    if len(projects.data) > 0 and len(scripts.data) > 0:
        print("\n🎉 SUCCESS! All data is being saved to the database!")
        print("\n✅ Check your Supabase dashboard:")
        print("   - Table Editor → profiles")
        print("   - Table Editor → projects") 
        print("   - Table Editor → scripts")
        print("\nYou should see your test data!")
        
except Exception as e:
    print(f"   ❌ Error: {e}")

print("\n6. Cleaning up...")
try:
    supabase.table('projects').delete().eq('user_id', user_id).execute()
    supabase.table('profiles').delete().eq('id', user_id).execute()
    print("   ✅ Test data cleaned up")
except Exception as e:
    print(f"   ⚠️  Cleanup error: {e}")

print("\n" + "=" * 70)
print("✅ DATABASE TEST COMPLETE!")
print("=" * 70)
