#!/usr/bin/env python3
"""
Minimal Coqui TTS test: generates speech and saves to a file.
"""
from TTS.api import TTS
import os

# Pick a model (XTTS for multi-lingual, multi-speaker, or use a single-speaker model)
# You can list available models with: TTS().list_models()
model_name = "tts_models/en/xtts/v2"  # XTTS v2 is multi-speaker, multi-lingual

# Download and load the model
print(f"Loading model: {model_name}")
tts = TTS(model_name)

# Text to speak
text = "Hello! This is a real voice generated by Coqui TTS XTTS v2. If you hear this, it works!"

# Output path
output_path = "coqui_tts_test.wav"

# Synthesize speech
print(f"Synthesizing speech to {output_path}...")
tts.tts_to_file(text=text, file_path=output_path)

# Check file
if os.path.exists(output_path):
    print(f"✅ Success! File saved: {output_path} ({os.path.getsize(output_path)} bytes)")
else:
    print("❌ Failed to generate audio file.") 